/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 23 10:23:39 GMT 2022
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Reference_ESTest extends Reference_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Reference reference0 = new Reference("4lQ2LH $mkR:H", (-573));
      int int0 = reference0.calculatePenalty(7000);
      assertEquals(5000, int0);
      assertEquals(5, reference0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Reference reference0 = new Reference("4lQ2LH $mkR:H", (-573));
      int int0 = reference0.calculatePenalty((-573));
      assertEquals(5, reference0.getDay());
      assertEquals(7000, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference("", 1);
      int int0 = reference0.calculatePenalty((-3));
      assertEquals(5000, int0);
      assertEquals(5, reference0.getDay());
  }
}
