/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 23 10:24:26 GMT 2022
 */

package ir.ramtung.impl2;

import org.junit.Test;
import static org.junit.Assert.*;
import ir.ramtung.impl2.Magazine;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Magazine_ESTest extends Magazine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Magazine magazine0 = new Magazine("", 0, 0, 0);
      magazine0.year = 1390;
      int int0 = magazine0.calculatePenalty(0);
      assertEquals(3000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Magazine magazine0 = new Magazine("Qd#|", 2, 2, 2);
      int int0 = magazine0.calculatePenalty(2);
      assertEquals(2000, int0);
      assertEquals(2, magazine0.getDay());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Magazine magazine0 = new Magazine("5$", 1551, 1551, 1551);
      int int0 = magazine0.calculatePenalty(1551);
      assertEquals(2, magazine0.getDay());
      assertEquals(3000, int0);
  }
}
