/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 23 10:22:59 GMT 2022
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Book book0 = new Book("@T,,?J!");
      boolean boolean0 = book0.isTitled("@T,,?J!");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Book book0 = new Book((String) null);
      String string0 = book0.getTitle();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Reference reference0 = new Reference((String) null);
      reference0.title = "";
      String string0 = reference0.getTitle();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Magazine magazine0 = null;
      try {
        magazine0 = new Magazine("", 5, 5);
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Documents with empty title are not allowed
         //
         verifyException("ir.ramtung.impl1.Document", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Book book0 = new Book("&-");
      boolean boolean0 = book0.isTitled("Mo l-aS");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Book book0 = new Book("&-");
      String string0 = book0.getTitle();
      assertEquals("&-", string0);
  }
}
