/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 23 10:23:06 GMT 2022
 */

package ir.ramtung.impl1;

import org.junit.Test;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DuplicateMemberEx_ESTest extends DuplicateMemberEx_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DuplicateMemberEx duplicateMemberEx0 = new DuplicateMemberEx("");
  }
}
