/*
 * This file was automatically generated by EvoSuite
 * Thu Jun 23 10:22:48 GMT 2022
 */

package ir.ramtung.impl1;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Member_ESTest extends Member_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Professor professor0 = new Professor("f'<");
      Professor professor1 = new Professor("ir.ramtung.impl1.Professor");
      boolean boolean0 = professor1.sameAs(professor0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Professor professor0 = new Professor("]L @S=#.s7p$kZ");
      boolean boolean0 = professor0.isNamed("]L @S=#.s7p$kZ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Student student0 = new Student("Empty student ID is not allowed", "Empty member name not allowed");
      student0.penalize(1596);
      int int0 = student0.getPrevPenalty();
      assertEquals(1596, int0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Professor professor0 = new Professor("ir.ramtung.impl1.Professor");
      professor0.prevPenalty = (-426);
      int int0 = professor0.getPrevPenalty();
      assertEquals((-426), int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Student student0 = new Student((String) null, (String) null);
      // Undeclared exception!
      try { 
        student0.sameAs((Member) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Student student0 = null;
      try {
        student0 = new Student("A8Pc#-O{h", "");
        fail("Expecting exception: Exception");
      
      } catch(Throwable e) {
         //
         // Empty member name not allowed
         //
         verifyException("ir.ramtung.impl1.Member", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Professor professor0 = new Professor("]L @S=#.s7p$kZ");
      int int0 = professor0.getPrevPenalty();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Professor professor0 = new Professor("]L @S=#.s7p$kZ");
      boolean boolean0 = professor0.sameAs(professor0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Student student0 = new Student("Empty student ID is not allowed", "Empty member name not allowed");
      boolean boolean0 = student0.isNamed("Empty student ID is not allowed");
      assertFalse(boolean0);
  }
}
